# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9  # pick the latest release
    hooks:
      # Linting + autofix
      - id: ruff
        args: [--fix]   # auto-fix what can be fixed
      # Formatting (Black-compatible)
      - id: ruff-format